synonims/Models/ErrorViewModel.cs
namespace synonims.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

synonims/Models/Match.cs
namespace synonims.Models
{
    public class Match
    {
        public int Id { get; set; }
        public int FirstWordId { get; set; }
        public int SecondWordId { get; set; }

    }
}

synonims/Models/SynonimsContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using synonims.Models;

#nullable disable

namespace synonims.Models
{
    public partial class SynonimsContext : DbContext
    {
        public SynonimsContext()
        {
        }

        public SynonimsContext(DbContextOptions<SynonimsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

synonims/Models/Word.cs
namespace synonims.Models
{
    /*this model is created for containing one word ex:wash
    second model called Match will containg id from word wash and id from its synonim. ex:clean
    This concept gives this logic both-way search possibility because it will hold both word ids */
    public class Word
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

synonims/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using synonims.Models;
using System.Diagnostics;

namespace synonims.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

synonims/Controllers/WordController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using synonims.Models;
using synonims.Services;

namespace synonims.Controllers
{
    public class WordController : Controller
    {
        public SynonimsContext _db;
        public IHttpContextAccessor _contextAccessor;
        public WordController(SynonimsContext db, IHttpContextAccessor contextAccessor)
        {
            _db = db;
            _contextAccessor = contextAccessor;
        }

        // GET: WordController
        public ActionResult Index()
        {
            return View("Add");
        }
        public ActionResult Search()
        {
            return View();
        }

        // GET: WordController/GetSynonym
        public ActionResult GetSynonym(string word)
        {
            try
            {
                MatchService matchService = new MatchService(_db);

                //Here I am taking value that was enterd in, and I am sending it to matchService
                //to get what is synonym for that word
                //After that I am calling view to display what matchService returned
                var SentWord = Request.Form["word"];

                var syns = matchService.GetSynonym(SentWord);

                return View("FindSynonyms", syns);
            }
            catch (Exception ex)
            {
                return View("Warning", ex);
            }
        }

        // GET: WordController/Create
        public ActionResult Create(string word, string synonym)
        {
            WordService wordService = new WordService(_db);

            synonym = Request.Form["synonym"];

            try
            {
                wordService.Create(word, synonym);
                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                
                return View("Warning", ex);
            }
        }


        
    }
}

synonims/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color:#00848c;
        }

        h1 {
            color: #edebd9;
        }

        h3 {
            color: #edebd9;
        }

        h5 {
            color: #fec20f;
        }

    </style>
</head>


<body>
    <div class="text-center">
        <h1 class="display-4">Welcome to synonym world :D</h1>
        <br />
        <br />
        <br />
        <br />
        <h3>
            Synonym: a word or phrase that means exactly or nearly the same as another word or phrase in the same language,
            for example shut is a synonym of close.
        </h3>
        <br />
        <br />
        <h5>
            Fun fact: Did you know that word synonym has its own synonym?
            Synonyms for word synonym are: equivalent, metonym, equivalent word etc. 
        </h5>
    </div>
</body>

</html>

synonims/Views/Shared/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #00848c;
        }

        input {
            border-radius: 11px;
            color: #fec20f;
            padding-top: 7px;
            padding-bottom: 7px;
        }

        label {
            color: #edebd9;
            font-size: 34px;
            margin-right: 5px;
        
        }

        h3 {
            color: #edebd9;
        }
        #form {
            width:100%;
            text-align:center;

        }
        #add{

            border-radius: 11px;
            color: #00848c;
            width:430px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            
        }
         #add:hover{
            background-color:#fec20f;
            text-align:center;
        }
    </style>
</head>


<body>
    <div id="form">
        <h3 class="display-5">Add your synonym</h3>
        <br />
        <form action="word/create" method="post">
            <label>Enter a new word:</label>
            <input name="word" />
            <br />
            <br />
            <label>Enter its synonym:</label>
            <input name="synonym" />
            <br />
            <br />
            <input id="add" type="submit" value="Add" />
        </form>
    </div>

</body>

</html>

synonims/Views/Shared/FindSynonyms.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        #form {
            width:100%;
            text-align:center;

        }
        body {
            background-color:#00848c;
        }
        h3{
            color: #edebd9;
        }
        p{
            color: #fec20f;
            font-size: 24px;
        }
    </style>
</head>

<body>
    <div id="form">
        <h3 class="display-5">Word that you enterd: @Model[0].Name </h3>

        <h3 class="display-5">Synonyms for this word:</h3>
        <br />

        @foreach (Word m in Model)
        {
            @if (m.Name != Model[0].Name)
            {
                <p>@m.Name</p>
                <br />
            }
        }

    </div>

</body>

</html>

synonims/Views/Shared/Search.cshtml
@{
    ViewData["Title"] = "Search";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color:#00848c;
        }

        h6 {
            color: #edebd9;
        }

        input {
            border-radius: 11px;
            color: #fec20f;
            padding-top: 7px;
            padding-bottom: 7px;
             
        }

        #search{

            border-radius: 11px;
            color: #00848c;
            width:330px;
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
            
        }
        #search:hover{
            background-color:#fec20f;
            text-align:center;
        }
        label {
            font-size: 34px;
            margin-right: 5px;
            color: #edebd9;
           
        }

        #form {
            width:100%;
            text-align:center;

        }
    </style>

</head>



<body>
    <div id="form">
         <form action="/Word/GetSynonym" method="post">
        <br />
        <h6 class="display-5">Type a word that you would like to see synonyms for</h6>
        <br />
        <label>Enter word:</label>
        <input name="word" />
        <br />
        <br />
        <input id="search" type="submit" value="Search" />
         </form>
    </div>
   
</body>
</html>

synonims/Views/Shared/Warning.cshtml
@{
    ViewData["Title"] = "Warning";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        #form {
            width: 100%;
            text-align: center;
        }

        body {
            background-color: #00848c;
        }

        h3 {
            color: #edebd9;
        }
        h4{
            color: #fec20f;
        }
    </style>
</head>

<body>
    <div id="form">
        <h3 class="display-5">Alert</h3>
        <br />
        <br />
        <h4>@Model.Message</h4>
    </div>

</body>

</html>

synonims/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Synonims</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/synonims.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Word" asp-action="Index">Add synonym</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Word" asp-action="Search">Search synoyms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
</body>
</html>